-- MySQL Script generated by MySQL Workbench
-- Sun Apr 20 11:58:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema paridhi-portal-2025
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `paridhi-portal-2025` ;

-- -----------------------------------------------------
-- Schema paridhi-portal-2025
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paridhi-portal-2025` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `paridhi-portal-2025` ;

-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`blacklisted_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`blacklisted_tokens` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`blacklisted_tokens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `black_listed_at` DATETIME(6) NOT NULL,
  `expires_at` DATETIME(6) NOT NULL,
  `token` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`users` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `college` VARCHAR(255) NULL DEFAULT NULL,
  `contact` VARCHAR(10) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `department` ENUM('AIDS', 'AIML', 'BA', 'BBA', 'BCA', 'BCOM', 'BSC', 'CE', 'CSBS', 'CSE', 'CYS', 'DS', 'ECE', 'EE', 'IT', 'LLB', 'LLM', 'MA', 'MBA', 'MCA', 'MCOM', 'ME', 'MSC', 'OTHERS') NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `is_profile_created` BIT(1) NOT NULL,
  `is_verified` BIT(1) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `profile_picture` VARCHAR(255) NULL DEFAULT NULL,
  `role` ENUM('ROLE_ADMIN', 'ROLE_SUPERADMIN', 'ROLE_USER') NOT NULL,
  `roll_no` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `year` ENUM('FIRST', 'SECOND', 'THIRD', 'FOURTH', 'PASSOUT', 'ALUMNI', 'OTHERS', 'NOT_APPLICABLE') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK6dotkott2kjsp8vw4d0m25fb7` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`contact_queries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`contact_queries` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`contact_queries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `contact` VARCHAR(255) NOT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `query` VARCHAR(1000) NOT NULL,
  `resolved` BIT(1) NOT NULL,
  `response` VARCHAR(1000) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `resolved_by_id` BIGINT NULL DEFAULT NULL,
  `is_resolved` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKnus2snqiushmit2pxpkbvip16` (`resolved_by_id` ASC) VISIBLE,
  CONSTRAINT `FKnus2snqiushmit2pxpkbvip16`
    FOREIGN KEY (`resolved_by_id`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`domain_posters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`domain_posters` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`domain_posters` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `domain_name` ENUM('CIVIL', 'CODING', 'ELECTRICAL', 'GAMING', 'GENERAL', 'ROBOTICS') NULL DEFAULT NULL,
  `poster_public_id` VARCHAR(255) NULL DEFAULT NULL,
  `poster_secure_url` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK93yricnpdd5icfjx1q68x5gwv` (`created_by` ASC) VISIBLE,
  INDEX `FKsjjn8xuuxw7d0ugq7claylj1d` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK93yricnpdd5icfjx1q68x5gwv`
    FOREIGN KEY (`created_by`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`),
  CONSTRAINT `FKsjjn8xuuxw7d0ugq7claylj1d`
    FOREIGN KEY (`updated_by`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`event_combos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`event_combos` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`event_combos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `combo_picture_public_id` VARCHAR(255) NULL DEFAULT NULL,
  `combo_picture_secure_url` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  `domain` ENUM('CIVIL', 'CODING', 'ELECTRICAL', 'GAMING', 'GENERAL', 'ROBOTICS') NULL DEFAULT NULL,
  `is_registration_open` BIT(1) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `registration_fee` DOUBLE NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKj31yrnc2n77dbra9es80c114y` (`created_by` ASC) VISIBLE,
  INDEX `FK5m6mon3e7ui0db7unvlucdwxa` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FK5m6mon3e7ui0db7unvlucdwxa`
    FOREIGN KEY (`updated_by`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`),
  CONSTRAINT `FKj31yrnc2n77dbra9es80c114y`
    FOREIGN KEY (`created_by`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`events` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`events` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(2000) NULL DEFAULT NULL,
  `domain` ENUM('CIVIL', 'CODING', 'ELECTRICAL', 'GAMING', 'GENERAL', 'ROBOTICS') NULL DEFAULT NULL,
  `event_date` DATETIME(6) NULL DEFAULT NULL,
  `event_picture_public_id` VARCHAR(255) NULL DEFAULT NULL,
  `event_picture_secure_url` VARCHAR(255) NULL DEFAULT NULL,
  `event_type` ENUM('MAIN', 'ON_SPOT') NULL DEFAULT NULL,
  `is_registration_open` BIT(1) NOT NULL,
  `max_players` INT NULL DEFAULT NULL,
  `min_players` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `prize_pool` DOUBLE NULL DEFAULT NULL,
  `registration_fee` DOUBLE NULL DEFAULT NULL,
  `rule_book` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `venue` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKmpv90a1lsx9lcxsj7xjcvvsxg` (`created_by` ASC) VISIBLE,
  INDEX `FKanc7ikmi2aiv7n7y4cndoqcf7` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FKanc7ikmi2aiv7n7y4cndoqcf7`
    FOREIGN KEY (`updated_by`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`),
  CONSTRAINT `FKmpv90a1lsx9lcxsj7xjcvvsxg`
    FOREIGN KEY (`created_by`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`event_combo_mappings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`event_combo_mappings` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`event_combo_mappings` (
  `combo_id` BIGINT NOT NULL,
  `event_id` BIGINT NOT NULL,
  PRIMARY KEY (`combo_id`, `event_id`),
  INDEX `FKa37es4tokg7x8vagwcurc5m5n` (`event_id` ASC) VISIBLE,
  CONSTRAINT `FK73a9lml01euxvcufy1qiuls1o`
    FOREIGN KEY (`combo_id`)
    REFERENCES `paridhi-portal-2025`.`event_combos` (`id`),
  CONSTRAINT `FKa37es4tokg7x8vagwcurc5m5n`
    FOREIGN KEY (`event_id`)
    REFERENCES `paridhi-portal-2025`.`events` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`event_coordinator_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`event_coordinator_details` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`event_coordinator_details` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,  -- Added primary key column
  `event_id` BIGINT NOT NULL,
  `coordinator_details` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),  -- Define primary key
  INDEX `FKbu9jjlob0wvwci85wn75e6s14` (`event_id` ASC) VISIBLE,
  CONSTRAINT `FKbu9jjlob0wvwci85wn75e6s14`
    FOREIGN KEY (`event_id`)
    REFERENCES `paridhi-portal-2025`.`events` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`galleries` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`galleries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `image_public_id` VARCHAR(255) NULL DEFAULT NULL,
  `image_secure_url` VARCHAR(255) NULL DEFAULT NULL,
  `batch_year` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKsj4tbw1nau24cgcmsu34ktan6` (`created_by` ASC) VISIBLE,
  INDEX `FKrahp56uayj76vv5pyjf7ipijg` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FKrahp56uayj76vv5pyjf7ipijg`
    FOREIGN KEY (`updated_by`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`),
  CONSTRAINT `FKsj4tbw1nau24cgcmsu34ktan6`
    FOREIGN KEY (`created_by`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`megatronix_team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`megatronix_team` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`megatronix_team` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `designation` ENUM('MEGATRON', 'MEMBER', 'APP_DEVELOPER', 'FRONTEND_DEVELOPER', 'BACKEND_DEVELOPER', 'FULL_STACK_DEVELOPER', 'BACKEND_DEVELOPER_AND_APP_DEVELOPER', 'BARA_BHATARI') NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `facebook_link` VARCHAR(255) NULL DEFAULT NULL,
  `github_link` VARCHAR(255) NULL DEFAULT NULL,
  `image_link` VARCHAR(255) NULL DEFAULT NULL,
  `instagram_link` VARCHAR(255) NULL DEFAULT NULL,
  `linked_in_link` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `year` ENUM('FIRST', 'FOURTH', 'SECOND', 'THIRD') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKgocajxl0gsb7rlmoqurnarkeq` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`mrd_registrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`mrd_registrations` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`mrd_registrations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `college` VARCHAR(255) NULL DEFAULT NULL,
  `contact` VARCHAR(255) NULL DEFAULT NULL,
  `department` ENUM('AIDS', 'AIML', 'BA', 'BBA', 'BCA', 'BCOM', 'BSC', 'CE', 'CSBS', 'CSE', 'CYS', 'DS', 'ECE', 'EE', 'IT', 'LLB', 'LLM', 'MA', 'MBA', 'MCA', 'MCOM', 'ME', 'MSC', 'OTHERS') NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `gid` VARCHAR(255) NOT NULL,
  `is_paid` BIT(1) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `registered_at` DATETIME(6) NULL DEFAULT NULL,
  `roll_no` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `year` ENUM('FIRST', 'SECOND', 'THIRD', 'FOURTH', 'PASSOUT', 'ALUMNI', 'OTHERS', 'NOT_APPLICABLE') NULL DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKpe4j5gu45nametct5w1nxugrx` (`gid` ASC) VISIBLE,
  INDEX `FK269c5i9w62dm16e280u2lbtdg` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK269c5i9w62dm16e280u2lbtdg`
    FOREIGN KEY (`user_id`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`otp_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`otp_tokens` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`otp_tokens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `otp` VARCHAR(6) NOT NULL,
  `used` BIT(1) NOT NULL,
  `user_id` BIGINT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `expires_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKq1f9i1og9qy5e59sjk036crl2` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKjyk2kyj8ul2bjqjpentlrpyi1`
    FOREIGN KEY (`user_id`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`password_reset_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`password_reset_tokens` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`password_reset_tokens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `expiry_date` DATETIME(6) NULL DEFAULT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `used` BIT(1) NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKla2ts67g4oh2sreayswhox1i6` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKk3ndxg5xp6v7wd4gjyusp15gq`
    FOREIGN KEY (`user_id`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`teams` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`teams` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `has_played` BIT(1) NOT NULL,
  `is_paid` BIT(1) NOT NULL,
  `is_qualified` BIT(1) NOT NULL,
  `position` ENUM('FIRST', 'SECOND', 'THIRD', 'NONE') NULL DEFAULT NULL,
  `registered_at` DATETIME(6) NULL DEFAULT NULL,
  `team_name` VARCHAR(255) NULL DEFAULT NULL,
  `tid` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `event_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKsjcq76oa92bm6gjbebp2spajm` (`event_id` ASC) VISIBLE,
  CONSTRAINT `FKsjcq76oa92bm6gjbebp2spajm`
    FOREIGN KEY (`event_id`)
    REFERENCES `paridhi-portal-2025`.`events` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`team_contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`team_contacts` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`team_contacts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,  -- Add this line for PK
  `team_id` BIGINT NOT NULL,
  `contact` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),  -- Add primary key constraint
  INDEX `FKmjt94w1dma7u748bo2wmnehg0` (`team_id` ASC) VISIBLE,
  CONSTRAINT `FKmjt94w1dma7u748bo2wmnehg0`
    FOREIGN KEY (`team_id`)
    REFERENCES `paridhi-portal-2025`.`teams` (`id`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`team_gids`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`team_gids` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`team_gids` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,  
  `team_id` BIGINT NOT NULL,   
  `gid` VARCHAR(255) NULL DEFAULT NULL,   
  PRIMARY KEY (`id`),  -- This line was missing
  INDEX `FKsv57brcmp861x5dgiosvtydm1` (`team_id` ASC) VISIBLE,   
  CONSTRAINT `FKsv57brcmp861x5dgiosvtydm1`     
    FOREIGN KEY (`team_id`)     
    REFERENCES `paridhi-portal-2025`.`teams` (`id`)
) ENGINE = InnoDB 
DEFAULT CHARACTER SET = utf8mb4 
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `paridhi-portal-2025`.`team_photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paridhi-portal-2025`.`team_photo` ;

CREATE TABLE IF NOT EXISTS `paridhi-portal-2025`.`team_photo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `category` ENUM('DEVELOPERS', 'MEGATRONS') NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `image_public_id` VARCHAR(255) NULL DEFAULT NULL,
  `image_secure_url` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `created_by` BIGINT NULL DEFAULT NULL,
  `updated_by` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKe2l3tv6eqco7hl4h46v2vhai7` (`created_by` ASC) VISIBLE,
  INDEX `FKnkk9f1sun37gths9vx438v2k8` (`updated_by` ASC) VISIBLE,
  CONSTRAINT `FKe2l3tv6eqco7hl4h46v2vhai7`
    FOREIGN KEY (`created_by`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`),
  CONSTRAINT `FKnkk9f1sun37gths9vx438v2k8`
    FOREIGN KEY (`updated_by`)
    REFERENCES `paridhi-portal-2025`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
