spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.application.name=${SPRING_APPLICATION_NAME}

app.base-url=${SPRING_APPLICATION_BASE_URL}

super-admin.default.email=${SUPER_ADMIN_EMAIL}
super-admin.default.password=${SUPER_ADMIN_PASSWORD}
super-admin.default.name=${SUPER_ADMIN_NAME}

# smtp configuration
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true