
spring.datasource.url=jdbc:mysql://${PROD_DB_HOST:localhost}:3306/${SPRING_APPLICATION_NAME}?createDatabaseIfNotExist=true}
spring.datasource.username=${PROD_DB_USERNAME:root}
spring.datasource.password=${PROD_DB_PASSWORD:12345}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update

# Production-specific HikariCP settings
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.register-mbeans=true

jwt.secret=${PROD_JWT_SECRET}
jwt.expiration=${PROD_JWT_EXPIRATION}